name: mania
description: Mania is an application which help streamers

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.4

  # --- Firebase

  google_sign_in: ^5.2.1
  firebase_core: ^1.10.5
  firebase_analytics: ^9.0.3
  firebase_auth: ^3.3.3
  firebase_messaging: ^11.2.3
  #  cloud_firestore: ^0.12.9+5

  # --- Twitch

  flutter_twitch: ^0.0.2
  flutter_twitch_auth: ^0.0.1

  # --- API

  dio: ^4.0.1
  retrofit: ^2.1.0
  logger: ^1.1.0
  json_annotation: ^4.3.0

  # --- Misc

  timeago: ^3.1.0
  string_similarity: ^2.0.0
  flutter_native_splash: ^1.3.1
  shared_preferences: ^2.0.8
  image_picker: ^0.8.4+4
  url_launcher: ^6.0.17
  pull_to_refresh: ^2.0.0
  auto_size_text: ^3.0.0
  material_design_icons_flutter: ^5.0.6595

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- API

  retrofit_generator: ^2.1.0+1
  build_runner: ^2.1.4
  json_serializable: ^6.0.1

  # --- Misc

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
  adaptive_icon_background: 'assets/icon/ic_background.png'
  adaptive_icon_foreground: 'assets/icon/ic_foreground.png'

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
